config/routes.rb
Rails.application.routes.draw do

root :to => 'users#new'

get '/signup' => 'users#new'
post '/users' => 'users#create'

get '/signin' => 'sessions#new'
post '/signin' => 'sessions#create'
get '/signout' => 'sessions#destroy'
  
  resources :lists do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
  validates :description, :presence => true
  scope :today, -> { where("created_at >=?", Time.now.beginning_of_day) }
  scope :ten_most_recent, -> { order(created_at: :desc).limit(10)}
  def self.not_done
    where(done: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authorize, only: [:index]


  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      # messing with alerts!
      flash[:notice] = "Rebecca is going to learn to Whiteboard like a pro!"
      flash[:alert] = "Dinosaurs are extinct!"
      redirect_to  lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list= List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to list_path(@task.list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to list_path(@task.list)
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to list_path(@task.list)
  end

private
  def task_params
    params.require(:task).permit(:description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
    <% else %>
      <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>
  
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<%= render "layouts/errors", :object => @list %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render "form" %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New List", new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form" %>

app/views/lists/show.html.erb
<% content_for(:title, "List | To Do") %>

<h1><%= @list.name %></h1>


<% if @list.tasks.any? %>
  <h4>Here are the tasks for this list:</h4>

  <ul>
    <% @list.tasks.each do |task| %>
      <li>
        <%= task.description %> |
        <%= link_to "Edit task", edit_list_task_path(@list, task) %> |
        <%= link_to "Delete", list_task_path(@list, task),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no tasks yet!</p>
<% end %>

<p><%= link_to "Add a task", new_list_task_path(@list) %></p>
<p><%= link_to "Edit list", edit_list_path(@list) %></p>
<p><%= link_to "Delete List", list_path(@list),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to lists", lists_path %></p>

app/views/tasks/_form.html.erb
<%= form_for [@list, @task] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <p><%= f.submit %></p>
<% end %>

<%= render('layouts/errors', :object => @task) %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render "form" %>

app/views/tasks/new.html.erb
<h1>New task for <%= @list.name %></h1>

<%= render "form" %>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>